stages:
    - build
    - test
    - deploy

composer:
  stage: build
  tags:
    - dev
  only:
    - staging
  image: lorisleiva/laravel-docker:latest
  before_script:
    - cp .env.docker .env
  script:
    - composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
    - php artisan key:generate
    - php artisan migrate
    - ln -s /var/www/storage/app/public/avatars public/avatars
    - ln -s /var/www/storage/app/public/banners public/banners
  cache:
    key: ${CI_COMMIT_REF_SLUG}-composer
    paths:
      - vendor/
  artifacts:
    paths:
      - vendor/
      - .env
    expire_in: 1 days
    when: always

phpunit:
  stage: test
  tags:
    - dev
  only:
    - staging
  dependencies:
    - composer
  script:
    - phpunit --coverage-text --colors=never

codestyle:
  stage: test
  tags:
    - dev
  only:
    - staging
  dependencies: []
  script:
    - phpcs --standard=PSR12 --extensions=php app/Http/Controllers/

deploy:
  stage: deploy
  only:
    - staging
  tags:
    - deploy
  image: tiangolo/docker-with-compose
  script:
    - docker-compose -f docker-compose.deploy.yml build
    - docker-compose -f docker-compose.deploy.yml down
    - docker-compose -f docker-compose.deploy.yml up -d --force-recreate
