stages:
    - build
    - test
    - deploy

composer:
  stage: build
  tags:
    - production
  only:
    - production
  image: lorisleiva/laravel-docker:latest
  before_script:
    - cp .env.production .env
    - echo "FILESYSTEM_DRIVER=spaces" >> .env
    - echo "${SPACES_KEY}" >> .env
    - echo "${SPACES_SECRET}" >> .env
    - echo "APP_URL=https://qchan.haakon.wtf/" >> .env
  script:
    - composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
    - php artisan key:generate

  cache:
    key: ${CI_COMMIT_REF_SLUG}-composer
    paths:
      - vendor/
  artifacts:
    paths:
      - vendor/
      - .env
    expire_in: 1 days
    when: always


codestyle:
  stage: test
  tags:
    - production
  only:
    - production
  dependencies: []
  script:
    - phpcs --standard=PSR12 --extensions=php app/Http/Controllers/

deploy:
  stage: deploy
  only:
    - production
  tags:
    - production
  image: tiangolo/docker-with-compose
  script:
    - docker-compose -f docker-compose.prod.yml down
    - docker-compose -f docker-compose.prod.yml up -d --force-recreate
  after_script:
    - docker exec qchan_api_1 php artisan migrate --force
