version: "3.8"

services:

  db:
    image: postgres:13.1-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - 'POSTGRES_PASSWORD=${DB_PASSWORD}'
      - 'POSTGRES_USER=${DB_USERNAME}'
    ports:
    - "5432:5432"


volumes:
  postgres:
    driver: local
