version: "3.8"

services:

  api:
    build:
      context: ./
      dockerfile: Dockerfile
    image: laravel
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - laravel

  node:
    build:
      context: ./
      dockerfile: node.dockerfile
    volumes:
      - ./:/var/www
    command: sh -c "npm install && npm run watch"
    networks:
      - laravel

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./nginx:/etc/nginx/conf.d
    networks:
      - laravel

  composer:
    image: composer
    command: composer install
    working_dir: /var/www
    volumes:
      - ./:/var/www

  postgres:
    image: postgres:13.2-alpine
    volumes:
      - pgsql_data:/var/lib/postgresql/data
    environment:
      - 'POSTGRES_PASSWORD=${DB_PASSWORD}'
    ports:
      - "5432:5432"
    networks:
      - laravel


volumes:
  pgsql_data:
    driver: local

networks:
  laravel:
    driver: bridge

