version: "3.8"

services:

  # Api
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - .:/var/www
    networks:
      - bridge

  # Webserver
  nginx:
    image: nginx:1.19.8-alpine
    ports:
      - 8000:80
    volumes:
      - .:/var/www
      - ./nginx:/etc/nginx/conf.d
    networks:
      - bridge

  postgres:
    image: postgres:13.2-alpine
    volumes:
      - pgsql_data:/var/lib/postgresql/data
    environment:
        - 'POSTGRES_PASSWORD=${DB_PASSWORD}'
        - 'POSTGRES_USER=${DB_USERNAME}'
    networks:
        - bridge

networks:
  bridge:
    driver: bridge

volumes:
  pgsql_data:
    driver: local
