version: "3.8"

services:

  # Api
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - .:/var/www
      - storage:/var/www/storage/app/public
    networks:
      - bridge

  # Webserver
  nginx:
    image: nginx:1.19.5-alpine
    ports:
      - 8000:80
    volumes:
      - .:/var/www
      - ./nginx:/etc/nginx/conf.d
    networks:
      - bridge

  db:
    image: postgres:13.1-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - 'POSTGRES_PASSWORD=${DB_PASSWORD}'
      - 'POSTGRES_USER=${DB_USERNAME}'
    networks:
      - bridge


networks:
  bridge:
    driver: bridge

volumes:
  postgres:
    driver: local
  storage:
    driver: local
