version: "3.8"

services:

  postgres:
    image: postgres:13.2-alpine
    volumes:
      - pgsql_data:/var/lib/postgresql/data
    environment:
      - 'POSTGRES_PASSWORD=${DB_PASSWORD}'
      - 'POSTGRES_USER=${DB_USERNAME}'
    ports:
    - "5432:5432"


volumes:
  pgsql_data:
    driver: local
